// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4T9DmL3gsEyPnn8eR_7aBJbL9y0ZlLQo',
    appId: '1:592166870653:web:4a3fd32c40ba112fe3db14',
    messagingSenderId: '592166870653',
    projectId: 'furever-home-dev',
    authDomain: 'furever-home-dev.firebaseapp.com',
    storageBucket: 'furever-home-dev.firebasestorage.app',
    measurementId: 'G-500F2082LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjWiyow580TwHUIJz9VlXUgBIap6-1kO0',
    appId: '1:592166870653:android:6a0b6a2f6aa2f586e3db14',
    messagingSenderId: '592166870653',
    projectId: 'furever-home-dev',
    storageBucket: 'furever-home-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFS0ESLEcMq_OzXnF5-z5GcDbEwdwYMoc',
    appId: '1:592166870653:ios:920cce17bb19e58ae3db14',
    messagingSenderId: '592166870653',
    projectId: 'furever-home-dev',
    storageBucket: 'furever-home-dev.firebasestorage.app',
    iosBundleId: 'com.example.fureverHomeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4T9DmL3gsEyPnn8eR_7aBJbL9y0ZlLQo',
    appId: '1:592166870653:web:4a9f83457c4af41ce3db14',
    messagingSenderId: '592166870653',
    projectId: 'furever-home-dev',
    authDomain: 'furever-home-dev.firebaseapp.com',
    storageBucket: 'furever-home-dev.firebasestorage.app',
    measurementId: 'G-VCMV7NG07K',
  );

}